:whale: Add Dockerfile :heavy_plus_sign: Add Pipfile :bug: Fix TypeError
I have added a Dockerfile to create a preconfigured container for ease of use.

I have also added a Pipfile since I will be using pipenv for dependencies and
environment control. Since I will be using pipevn I changed the pythonapp.yml
to match this for githubs workflow.

```
 pipenv run python gen-key.py
Traceback (most recent call last):
  File "gen-key.py", line 32, in <module>
    der[1] = octet_der.encode()
TypeError: 'NoneType' object does not support item assignment

```
Having already experimented with gen-key.py I was getting a TypeError. I have
corrected what I believe to be the issue.

https://pycryptodome.readthedocs.io/en/latest/src/util/asn1.html#Crypto.Util.asn1.DerSequence