:heavy_minus_sign: Remove Unittest
I have removed unittest because I am getting the following error.

```
ERROR: ERROR: Could not find a version that matches unittest
No versions found
```

This is a temp fix and should be addressed better.